version: '3.9'
services:
  server:
    container_name: django
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
    volumes:
      - ./src:/usr/src/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./env/server.env
      - /env/cache.env
  redis:
    image: "redis:alpine"
